### ISSUE TITLE
Document a list of utilities required by the install scripts

### ISSUE THREAD

**Issue by aplowman** [hpcflow/install-scripts#55]
E.g. `curl`, `unzip`, etc

**Comment by cjfullerton** [comment]
Updating this list as I go...

## Bash

Assume commands/built-ins (eg trap, shift, while, etc) are standard across all bash installs - is this correct?

### utitlities
- mktemp 
- curl
- grep
- unzip

## Powershell

Have to be wary that behind the scenes implementation of cmdlets will vary between versions of powershell - have already seen this with Invoke-WebRequest in Windows sandbox.

Cmdlets used

**Comment by cjfullerton** [comment]
I think the intention was for the list of required software to be added to the online documentation on the installer page.

@aplowman can you confirm?

If so, #74 doesn't close this issue.

**Comment by aplowman** [comment]
Yeah, we want a check in the script, but it should also be documented on the install web page somewhere, maybe under a "Requirements" sub-heading under https://docs.matflow.io/stable/installation.html#matflow-cli (and for hpcflow as well).
