### ISSUE TITLE
Incorrect alias path added in powershell alias file

### ISSUE THREAD

**Issue by aplowman** [hpcflow/install-scripts#62]
Perhaps this is known, but after running the install script using the command from the docs site: 

```ps1
& $([scriptblock]::Create((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/hpcflow/install-scripts/main/src/install-matflow.ps1'))) -PreRelease -UnivLink
```

I have ended up with an entry like this in my `matflow_aliases.csv` file:

```
"matflow-dev","C:\Users\username\AppData\Local\matflow\matflow-v0.3.0a61-win-dir.zip","","None"
```

i.e. a non-existent path to the zip file rather than "installed executable".

**Comment by cjfullerton** [comment]
Should be an easy fix - the wrong variable is being added to the alias file (the name of the downloaded file, rather than the name of the executable one).

**Comment by cjfullerton** [comment]
The integration tests do check that the *-dev symlinks and aliases are working properly, so not sure how this one slipped past. It's possible tests are using the --onefile flag...

**Comment by cjfullerton** [comment]
I've changed the integration test so that it runs the script from the documentation and then it checks `matflow-dev test`. 

This looks like it's working (at least on the runner): https://github.com/hpcflow/install-scripts/actions/runs/6111658001/job/16587387568
